-- Tiers (DESIGN §11.6), key rotation (§11.2c) and the invalidation path that
-- makes a revocation take effect (§11.2c, risk W11).
--
-- The SQLite file of the same version carries the full rationale. What differs
-- here is spelling only: BIGINT for microsecond timestamps, BOOLEAN for the
-- flags, GENERATED AS IDENTITY for the invalidation sequence, and IF NOT EXISTS
-- on the ALTERs because PostgreSQL supports it and SQLite does not.
--
-- request_logs is partitioned by range here (§9.5). ADD COLUMN on the parent
-- propagates to every existing and future partition, so the ledger's new
-- secret_id column needs no per-partition step.

ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS tier        TEXT NOT NULL DEFAULT '';
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS pended_at   BIGINT;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS pend_reason TEXT NOT NULL DEFAULT '';

CREATE TABLE api_key_secrets (
    id          TEXT    PRIMARY KEY,
    key_id      TEXT    NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    generation  BIGINT  NOT NULL DEFAULT 1,
    lookup      TEXT    NOT NULL,
    token_hash  TEXT    NOT NULL,
    hash_scheme TEXT    NOT NULL CHECK (hash_scheme IN ('dorang_v1', 'legacy_sha256')),
    key_label   TEXT    NOT NULL DEFAULT '',
    is_current  BOOLEAN NOT NULL DEFAULT true,
    created_at  BIGINT  NOT NULL,
    expires_at  BIGINT,
    revoked_at  BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS api_key_secrets_lookup_key ON api_key_secrets (lookup);
CREATE INDEX IF NOT EXISTS api_key_secrets_key_idx ON api_key_secrets (key_id, generation DESC);
CREATE UNIQUE INDEX IF NOT EXISTS api_key_secrets_current_key
    ON api_key_secrets (key_id) WHERE is_current;

INSERT INTO api_key_secrets
    (id, key_id, generation, lookup, token_hash, hash_scheme, key_label, is_current, created_at)
SELECT id || '.1', id, 1, lookup, token_hash, hash_scheme, key_label, true, created_at
  FROM api_keys
    ON CONFLICT DO NOTHING;

CREATE TABLE key_invalidations (
    seq        BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id     TEXT    NOT NULL,
    lookups    TEXT    NOT NULL DEFAULT '[]',
    cause      TEXT    NOT NULL DEFAULT 'unspecified',
    created_at BIGINT  NOT NULL
);

CREATE INDEX IF NOT EXISTS key_invalidations_seq_idx ON key_invalidations (seq);
CREATE INDEX IF NOT EXISTS key_invalidations_created_idx ON key_invalidations (created_at);

ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS secret_id TEXT;
