import { createRequire } from 'node:module';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fixture=JSON.parse(await readFile(process.env.DORANG_CONSOLE_FIXTURE||'/tmp/dorang-console-fixture.json','utf8'));
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1050},locale:'en-US'});
const page=await context.newPage();
const errors=[];const userEmail='console-'+Date.now()+'@example.test';page.on('pageerror',e=>errors.push(e.message));
await mkdir('/tmp/dorang-console-screenshots',{recursive:true});
try{
 await page.goto(fixture.url+'/ui/login');
 await page.locator('#locale-select').selectOption('ko');
 await page.locator('[name=key]').fill('invalid-browser-test-key');
 await page.locator('form button[type=submit]').click();
 assert.match(await page.locator('.alert').innerText(),/관리 권한/);
 await page.locator('#locale-select').selectOption('en');
 await page.locator('[name=key]').fill(fixture.token);
 await Promise.all([page.waitForURL('**/ui/**'),page.locator('form button[type=submit]').click()]);
 await page.goto(fixture.url+'/ui/overview');
 await page.waitForFunction(()=>document.querySelector('#stream-state')?.textContent==='Live');
 await page.locator('#model-metrics a').first().waitFor();
 assert.match(await page.locator('#model-metrics').innerText(),/m1/);
 assert.match(await page.locator('#token-breakdown').innerText(),/Cache read/);
 await page.waitForFunction(()=>document.querySelector('#traffic-line')?.getAttribute('d')?.includes('L'));
 await page.screenshot({path:'/tmp/dorang-console-screenshots/overview-en.png',fullPage:true});
 await page.locator('#locale-select').selectOption('ko');
 assert.equal(await page.locator('h1').innerText(),'개요');
 assert.equal(await page.title(),'개요 — dorang');
 assert.equal(await page.locator('#stream-state').innerText(),'실시간');
 assert.match(await page.locator('#token-breakdown').innerText(),/캐시 읽기/);
 await page.screenshot({path:'/tmp/dorang-console-screenshots/overview-ko.png',fullPage:true});
 await page.reload();await page.locator('#model-metrics a').first().waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'ko');
 await page.locator('#locale-select').selectOption('en');
 await page.goto(fixture.url+'/ui/requests');
 await page.locator('#live-request-rows button').first().waitFor();
 await page.locator('#live-pause').click();const frozen=await page.locator('#live-request-rows').innerText();await page.waitForTimeout(2400);assert.equal(await page.locator('#live-request-rows').innerText(),frozen);
 await page.locator('#live-request-rows button').first().click();
 assert.match(await page.locator('#request-detail-content').innerText(),/Cache write tokens\s+5/);
 assert.match(await page.locator('#request-detail-content').innerText(),/Reasoning tokens\s+8/);
 await page.locator('#request-dialog [data-close-dialog]').click();
 await page.locator('#request-search').fill('nothing-matches');assert.match(await page.locator('#live-request-rows').innerText(),/No requests/);
 await page.locator('#request-search').fill('m1');assert.match(await page.locator('#live-request-rows').innerText(),/m1/);
 await page.screenshot({path:'/tmp/dorang-console-screenshots/requests.png',fullPage:true});
 await page.goto(fixture.url+'/ui/metrics');
 await page.locator('.metric-family').first().waitFor();
 await page.locator('#metric-search').fill('dorang_model_tokens_total');
 await page.locator('.metric-family').first().evaluate(el=>{el.open=true;});
 assert.match(await page.locator('#metric-families').innerText(),/cache_write/);
 assert.match(await page.locator('#metric-families').innerText(),/reasoning/);
 await page.screenshot({path:'/tmp/dorang-console-screenshots/metrics.png',fullPage:true});
 for(const path of ['credentials','capacity','analytics','budgets','pricing','catalog','operations','keys','users','models']){
  const response=await page.goto(fixture.url+'/ui/'+path);assert.equal(response.status(),200,path);
  assert.equal(await page.locator('main').count(),1,path);
 }
 await page.goto(fixture.url+'/ui/pricing');
 await page.locator('[name=model]').fill('m1-upstream');await page.locator('[name=provider]').fill('p1');
 await page.locator('[name=prompt_tokens]').fill('1000000');await page.locator('[name=completion_tokens]').fill('500000');
 await Promise.all([page.waitForURL('**/ui/pricing?**'),page.getByRole('button',{name:'Calculate price',exact:true}).click()]);
 assert.match(await page.locator('.metric-grid').innerText(),/Billed cost\s+5/);
 await page.goto(fixture.url+'/ui/users');
 await page.getByText('Register a user',{exact:true}).click();
 await page.locator('[name=user_email]').fill(userEmail);
 await page.locator('[name=user_name]').fill('Console Browser');
 await Promise.all([page.waitForURL('**/ui/users'),page.getByRole('button',{name:'create user',exact:true}).click()]);
 assert.match(await page.locator('main').innerText(),new RegExp(userEmail));
 // Exercise a Korean budget mutation through the same CSRF/session forms.
 const userRow=page.locator('tbody tr').filter({hasText:userEmail});
 const editURL=await userRow.getByRole('link',{name:'edit',exact:true}).getAttribute('href');
 const userID=new URL(editURL,fixture.url).searchParams.get('user_id');
 await page.goto(fixture.url+'/ui/budgets');await page.locator('#locale-select').selectOption('ko');
 await page.locator('details > summary').first().click();
 await page.locator('[name=subject_kind]').selectOption('user');await page.locator('[name=subject_id]').fill(userID);
 await page.locator('[name=max_budget]').fill('12.34');assert.equal(await page.locator('[name=soft_budget]').isDisabled(),true);await page.locator('[name=budget_duration]').fill('monthly');
 page.once('dialog',d=>d.accept());await Promise.all([page.waitForURL('**/ui/budgets'),page.getByRole('button',{name:'예산 저장',exact:true}).click()]);
 assert.match(await page.locator('.banner.ok').innerText(),/예산/);
 const budgetRow=page.locator('tbody tr').filter({hasText:userID});assert.match(await budgetRow.innerText(),/12.34/);
 await budgetRow.locator('a').click();assert.equal(await page.locator('[name=max_budget]').inputValue(),'12.34');
 await page.locator('[name=max_budget]').fill('15.67');page.once('dialog',d=>d.accept());
 await Promise.all([page.waitForURL('**/ui/budgets'),page.getByRole('button',{name:'예산 저장',exact:true}).click()]);
 assert.match(await page.locator('tbody tr').filter({hasText:userID}).innerText(),/15.67/);
 await page.locator('#locale-select').selectOption('en');
 page.once('dialog',d=>d.accept());await Promise.all([page.waitForURL('**/ui/budgets'),page.locator('tbody tr').filter({hasText:userID}).getByRole('button',{name:'Remove ceiling',exact:true}).click()]);
 await page.goto(fixture.url+'/ui/overview');await page.locator('#model-metrics a').first().waitFor();
 await page.evaluate(()=>localStorage.setItem('dorang.theme','dark'));await page.reload();await page.locator('#model-metrics a').first().waitFor();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.screenshot({path:'/tmp/dorang-console-screenshots/dark.png',fullPage:true});
 await page.goto(fixture.url+'/ui/operations');
 await page.getByRole('button',{name:'Go to screen',exact:false}).click();
 await page.locator('#command-query').fill('budget');await page.locator('#command-query').press('Enter');await page.waitForURL('**/ui/budgets');

 // Follow the complete provider -> account -> discovered model workflow.
 await page.goto(fixture.url+'/ui/setup');
 const providerID='browser-provider-'+Date.now(),accountID='browser-account-'+Date.now();
 const providerForm=page.locator('#providers form');await page.locator('#providers summary').click();
 await providerForm.locator('[name=id]').fill(providerID);await providerForm.locator('[name=kind]').selectOption('openai');await providerForm.locator('[name=base_url]').fill(fixture.upstream_url);
 await providerForm.getByRole('button',{name:'Save connection',exact:true}).click();await page.waitForURL('**/ui/setup?**#accounts');
 const providerRow=page.locator('#providers tbody tr').filter({hasText:providerID});assert.match(await providerRow.innerText(),/Applied/);
 await providerRow.getByRole('link',{name:'Add account',exact:true}).click();
 const accountForm=page.locator('#accounts form');await accountForm.locator('[name=id]').fill(accountID);await accountForm.locator('[data-key-value]').fill('browser-key-1');
 await accountForm.getByRole('button',{name:'Save account',exact:true}).click();await page.waitForURL('**/ui/setup?**#service-models');
 let accountRow=page.locator('#accounts tbody tr').filter({hasText:accountID});assert.match(await accountRow.innerText(),/Applied/);
 await accountRow.getByRole('button',{name:'Check connection & models',exact:true}).click();await page.locator('#discovery-result a').first().waitFor();
 await page.locator('#discovery-result').getByRole('link',{name:'browser-model',exact:true}).click();
 const modelForm=page.locator('[data-model-form]');assert.equal(await modelForm.locator('[name=upstream]').inputValue(),'browser-model');assert.equal(await modelForm.locator('[name=credential]').inputValue(),accountID);
 await modelForm.locator('[name=model]').fill('browser-service-'+Date.now());const serviceName=await modelForm.locator('[name=model]').inputValue();
 await modelForm.getByRole('button',{name:'Add model binding',exact:true}).click();await page.waitForURL('**/ui/setup?**#service-models');
 assert.match(await page.locator('#service-models tbody tr').filter({hasText:serviceName}).innerText(),/Disabled/);
 await page.goto(fixture.url+'/ui/models');
 await page.locator('tbody tr').filter({hasText:serviceName}).getByRole('button',{name:'enable',exact:true}).click();
 await page.waitForURL('**/ui/models');await page.goto(fixture.url+'/ui/setup');
 assert.match(await page.locator('#service-models tbody tr').filter({hasText:serviceName}).innerText(),/Enabled/);
 accountRow=page.locator('#accounts tbody tr').filter({hasText:accountID});await accountRow.getByRole('link',{name:'Update key / authentication',exact:true}).click();
 await page.locator('#locale-select').selectOption('ko');assert.equal(await page.locator('h1').innerText(),'업스트림 연결');
 assert.equal(await page.locator('[data-key-value]').inputValue(),'');await page.locator('#accounts [name=source]').selectOption('secret');await page.locator('[data-key-value]').fill('browser-key-2');
 await page.locator('#accounts').getByRole('button',{name:'인증 정보 갱신',exact:true}).click();await page.waitForURL('**/ui/setup?**#accounts');
 await page.locator('#accounts tbody tr').filter({hasText:accountID}).getByRole('button',{name:'연결 확인 및 모델 조회',exact:true}).click();await page.locator('#discovery-result a').first().waitFor();
 assert.match(await page.locator('#discovery-result').innerText(),/연결을 확인/);
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:'/tmp/dorang-console-screenshots/setup-ko.png',fullPage:true});
 await page.locator('#locale-select').selectOption('en');
 await page.setViewportSize({width:390,height:844});
 await page.goto(fixture.url+'/ui/overview');await page.locator('#model-metrics a').first().waitFor();
 const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(sizes.scroll<=sizes.width+1,JSON.stringify(sizes));
 await page.screenshot({path:'/tmp/dorang-console-screenshots/mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: SSE, cache dimensions, pause, filters, detail, metrics, navigation, pricing, user creation, i18n persistence, provider/account onboarding, model discovery/binding, key rotation and mobile layout');
}catch(err){console.error('UI alerts:',await page.locator('.alert').allTextContents());await page.screenshot({path:'/tmp/dorang-console-screenshots/failure.png',fullPage:true});throw err;}finally{await browser.close();}
