package batch

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sync"
)

// DiskBlobs stores file content on a local filesystem.
//
// It is the default [Blobs] implementation: a batch input file is large, written
// once, and read many times at random offsets, which is what a filesystem is
// for. A cluster shares one by pointing every node at the same mount, or
// replaces it with an object-store implementation — the interface is three
// methods precisely so that swapping it is not a project.
type DiskBlobs struct {
	root string
}

// NewDiskBlobs prepares root, creating it if necessary.
func NewDiskBlobs(root string) (*DiskBlobs, error) {
	if root == "" {
		return nil, errors.New("batch: blob root is required")
	}
	if err := os.MkdirAll(root, 0o700); err != nil {
		return nil, err
	}
	return &DiskBlobs{root: root}, nil
}

// path resolves a ref, rejecting anything that is not a plain identifier.
//
// Refs are generated by this package, so nothing should ever fail here — which
// is exactly why it is checked. The day a ref becomes caller-influenced, this is
// the line between "a file id" and "any path on the host".
func (d *DiskBlobs) path(ref string) (string, error) {
	if ref == "" || len(ref) > 255 {
		return "", fmt.Errorf("%w: blob ref %q", ErrInvalidRequest, ref)
	}
	for i := 0; i < len(ref); i++ {
		c := ref[i]
		ok := c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' ||
			c == '-' || c == '_' || c == '.'
		if !ok {
			return "", fmt.Errorf("%w: blob ref %q", ErrInvalidRequest, ref)
		}
	}
	if ref == "." || ref == ".." {
		return "", fmt.Errorf("%w: blob ref %q", ErrInvalidRequest, ref)
	}
	return filepath.Join(d.root, ref), nil
}

// Put writes content atomically: a reader either sees the previous content or
// the new content, never a partial write, because the bytes land in a temporary
// file that is renamed into place.
func (d *DiskBlobs) Put(ctx context.Context, ref string, r io.Reader) (int64, error) {
	dst, err := d.path(ref)
	if err != nil {
		return 0, err
	}
	tmp, err := os.CreateTemp(d.root, ".tmp-*")
	if err != nil {
		return 0, err
	}
	tmpName := tmp.Name()
	defer func() {
		tmp.Close()
		os.Remove(tmpName)
	}()

	n, err := io.Copy(tmp, &ctxReader{ctx: ctx, r: r})
	if err != nil {
		return n, err
	}
	if err := tmp.Sync(); err != nil {
		return n, err
	}
	if err := tmp.Close(); err != nil {
		return n, err
	}
	if err := os.Chmod(tmpName, 0o600); err != nil {
		return n, err
	}
	if err := os.Rename(tmpName, dst); err != nil {
		return n, err
	}
	return n, nil
}

// Open returns the content for reading at arbitrary offsets.
func (d *DiskBlobs) Open(ctx context.Context, ref string) (io.ReadSeekCloser, error) {
	p, err := d.path(ref)
	if err != nil {
		return nil, err
	}
	f, err := os.Open(p)
	if errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("%w: blob %s", ErrNotFound, ref)
	}
	return f, err
}

// Remove deletes the content. Removing what is not there is not an error.
func (d *DiskBlobs) Remove(ctx context.Context, ref string) error {
	p, err := d.path(ref)
	if err != nil {
		return err
	}
	if err := os.Remove(p); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

// ctxReader makes a long copy interruptible. Without it, a 200 MiB upload from a
// slow client cannot be cancelled once io.Copy has started.
type ctxReader struct {
	ctx context.Context
	r   io.Reader
}

func (c *ctxReader) Read(p []byte) (int, error) {
	if err := c.ctx.Err(); err != nil {
		return 0, err
	}
	return c.r.Read(p)
}

// MemBlobs keeps content in memory.
//
// It exists for tests and for a notebook-profile run that wants no files on
// disk. It is not durable and does not pretend to be: a restart loses every
// byte, and a batch resumed against it will not find its input file.
type MemBlobs struct {
	mu   sync.Mutex
	data map[string][]byte
}

// NewMemBlobs returns an empty in-memory blob store.
func NewMemBlobs() *MemBlobs { return &MemBlobs{data: make(map[string][]byte)} }

// Put stores a copy of the content.
func (m *MemBlobs) Put(ctx context.Context, ref string, r io.Reader) (int64, error) {
	b, err := io.ReadAll(&ctxReader{ctx: ctx, r: r})
	if err != nil {
		return 0, err
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	m.data[ref] = b
	return int64(len(b)), nil
}

// Open returns a reader over a snapshot of the content.
func (m *MemBlobs) Open(ctx context.Context, ref string) (io.ReadSeekCloser, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	b, ok := m.data[ref]
	if !ok {
		return nil, fmt.Errorf("%w: blob %s", ErrNotFound, ref)
	}
	return nopSeekCloser{bytes.NewReader(b)}, nil
}

// Remove deletes the content.
func (m *MemBlobs) Remove(ctx context.Context, ref string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.data, ref)
	return nil
}

type nopSeekCloser struct{ *bytes.Reader }

func (nopSeekCloser) Close() error { return nil }
