-- The budget reservation columns, removed (DESIGN §6.4, §9.6).
--
--   budget_state.reserved_nano
--   budget_state.reserved_until
--
-- These two columns were the storage of a SECOND budget reservation mechanism.
-- internal/store shipped ReserveBudget / SettleBudget / ReleaseReservation /
-- SweepExpiredReservations over them, internal/cluster ran a leader job that
-- swept them every tick, and DESIGN §6.4 R1-19 described them as the safety net
-- for a process killed between reserve and settle. All of it was tested and
-- none of it had a caller: `ReserveBudget` had zero non-test call sites in the
-- tree, so `reserved_nano` was zero in every row of every deployment and the
-- sweep's `WHERE reserved_nano > 0` was a query per tick against a predicate
-- that could not match.
--
-- The mechanism that runs is the lease block of §9.6. `cluster.Ledger` draws a
-- block, charges it to `spent_nano` in FULL before a unit of it is handed out,
-- and holds the units in memory behind an atomic; the store sees a write per
-- block rather than per request, which is the whole reason a synchronous budget
-- reservation is affordable. Reserving through this table would have been the
-- write-per-request arrangement §9.6 exists to avoid, and it is why the two
-- could never be merged: charging a block AND reserving against it would count
-- the same money twice.
--
-- The capability the columns claimed is not dropped with them. "A process
-- killed between reserve and settle must not lock that amount forever" is
-- served by `quota_leases.expires_at` plus the leader's lease-reclaim pass,
-- which returns `amount - used` of every lease whose TTL has passed. That net
-- is strictly wider than the one removed: it also covers a node that dies
-- holding a block already charged to `spent_nano`, which no reservation sweep
-- could ever have reclaimed.
--
-- Dropping rather than leaving them inert is deliberate. A column nothing
-- writes is the same defect as a function nothing calls, in a medium that has
-- no compiler to notice; and `spent_nano + reserved_nano` was still being read
-- by `Ledger.readCounter`, where an unreachable term reads like an interlock
-- between two live mechanisms.
--
-- No data is lost: the columns are `0` and `NULL` in every row that exists,
-- because nothing ever wrote anything else into them.
ALTER TABLE budget_state DROP COLUMN reserved_nano;
ALTER TABLE budget_state DROP COLUMN reserved_until;
